services:
  - type: web
    name: portal-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_ORIGIN
        value: https://frontend-xi-nine-84.vercel.app
      - key: NODE_ENV
        value: production
